services:
  Marketplace.coursesCounter.CoursesCounterRepository:
    class: ../../../../../Contexts/Marketplace/CoursesCounter/infrastructure/persistence/mongo/MongoCoursesCounterRepository
    arguments: ["@Shared.ConnectionManager"]

  Marketplace.coursesCounter.CoursesCounterIncrementer:
    class: ../../../../../Contexts/Marketplace/CoursesCounter/application/Increment/CoursesCounterIncrementer
    arguments: [
      "@Marketplace.coursesCounter.CoursesCounterRepository",
      "@Shared.EventBus"
      ]

  Marketplace.coursesCounter.IncrementCoursesCounterOnCourseCreated:
    class: ../../../../../Contexts/Marketplace/CoursesCounter/application/Increment/IncrementCoursesCounterOnCourseCreated
    arguments: ["@Marketplace.coursesCounter.CoursesCounterIncrementer"]
    tags:
      - { name: 'domainEventSubscriber' }

  Marketplace.coursesCounter.CoursesCounterFinder:
    class: ../../../../../Contexts/Marketplace/CoursesCounter/application/Find/CoursesCounterFinder
    arguments: ["@Marketplace.coursesCounter.CoursesCounterRepository"]

  Marketplace.coursesCounter.FindCoursesCounterQueryHandler:
    class: ../../../../../Contexts/Marketplace/CoursesCounter/application/Find/FindCoursesCounterQueryHandler
    arguments: ["@Marketplace.coursesCounter.CoursesCounterFinder"]
    tags:
      - { name: 'queryHandler' }
