services:
  Marketplace.coursesCounter.CoursesCounterFinder:
    class: ../../../../../Contexts/Marketplace/CoursesCounter/application/Find/CoursesCounterFinder
    arguments: ['@Marketplace.coursesCounter.CoursesCounterRepository']

  Marketplace.coursesCounter.CoursesCounterRepository:
    class: ../../../../../Contexts/Marketplace/CoursesCounter/infrastructure/persistence/mongo/MongoCoursesCounterRepository
    arguments: ['@Shared.ConnectionManager']

  Marketplace.coursesCounter.FindCoursesCounterQueryHandler:
    class: ../../../../../Contexts/Marketplace/CoursesCounter/application/Find/FindCoursesCounterQueryHandler
    arguments: ['@Marketplace.coursesCounter.CoursesCounterFinder']
    tags:
      - { name: 'queryHandler' }
