services:

  Apps.marketplace.controllers.CatalogPutController:
    class: ../../controllers/CatalogPutController
    arguments: ["@Shared.CommandBus"]

  Apps.marketplace.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []
