services:
  Marketplace.courses.CourseRepository:
    class: ../../../../../Contexts/Marketplace/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@Shared.ConnectionManager']

  Marketplace.courses.CourseCreator:
    class: ../../../../../Contexts/Marketplace/Courses/application/CourseCreator
    arguments: ['@Marketplace.courses.CourseRepository', '@Shared.EventBus']

  Marketplace.courses.CreateCourseCommandHandler:
    class: ../../../../../Contexts/Marketplace/Courses/application/CreateCourseCommandHandler
    arguments: ['@Marketplace.courses.CourseCreator']
    tags:
      - { name: 'commandHandler' }

  Backoffice.courses.RabbitMqConfig:
    factory:
      class: ../../../../../Contexts/Backoffice/Courses/infrastructure/EventBus/RabbitMq/RabbitMqConfigFactory
      method: 'createConfig'
