imports:
  - { resource: ./application.yaml }

services:
  Marketplace.EnvironmentArranger:
    class: ../../../../tests/contexts/shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Shared.ConnectionManager']
